Support opting out of Advisory Lock
brendon/positioning pull request #15
Opened 2024-06-28 17:22 UTC by joaomarcos96

There are scenarios where Advisory Lock is not the best approach.

I have added the support to disable it by passing the `use_advisory_lock` as `false` when declaring positing.

2024-06-28 21:57 UTC, brendon requested changes
Hi @joaomarcos96, thanks for this. It's good to see options in this space :)

Just a few little changes but overall I like the idea of making this optional.

Could you perhaps outline your reason why an Advisory Lock doesn't work in your situation? This could potentially be added to the `README` so that other people can consider the reason in light of their situation.

For some reason the GitHub Action for CI isn't triggering on your PR. I'll try to figure that out :)

2024-06-28 21:57 UTC, brendon commented on README.md
> +positioned on: :list, use_advisory_lock: false
Can we just call it `advisory_lock: false`?

2024-06-28 21:57 UTC, brendon commented on README.md
> +You can opt out of Advisory Lock by setting `use_advisory_lock` as `false` when declaring positioning:
`advisory_lock` to `false`

2024-06-28 21:57 UTC, brendon commented on README.md
> +  list.items.create(name: "My list item")
It might be helpful to also show an `update` and `destroy` case here if they're particularly different scenarios?

2024-06-28 21:57 UTC, brendon commented on lib/positioning.rb
> +            advisory_lock = AdvisoryLock.new(base_class, column)
We'd have to rename the local variable. Perhaps to `advisory_lock_callback`?

2024-06-28 21:57 UTC, brendon commented on test/test_positioning.rb
> +            list.with_lock do
I think my original test doesn't test updates either? I think have a go at it here and see how you get on and I might back-fill the other one too.

2024-06-28 21:57 UTC, brendon commented on test/test_positioning.rb
> +    list.destroy
We should probably have tests for destruction too.

2024-07-05 03:30 UTC, joaomarcos96 commented
@brendon I have done what was suggested and updated the readme as well

2024-07-05 19:45 UTC, brendon approved these changes

2024-07-05 19:45 UTC, merged

2024-07-05 19:46 UTC, brendon commented
Amazing! Thanks @joaomarcos96 :D Will release a new version now :)